development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "e8bb43d265fd2c6fba33b2934fbcf4618c48086c49f3cabc37c870255bcd37ae"
  signature_expiration: 3600 # one hour
